In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.0563e-35, 7.3288e-43, 4.4217e-36],
        [7.3288e-43, 4.4222e-36, 7.3288e-43],
        [4.4085e-36, 7.3288e-43, 1.2031e-35],
        [7.3288e-43, 1.2030e-35, 7.3288e-43],
        [1.0600e-35, 7.3288e-43, 1.0599e-35]])


In [3]:
x = torch.randn(5, 3)
print(x)

tensor([[ 0.0765,  2.3322, -0.1619],
        [ 0.0143,  0.3767,  0.8207],
        [-0.7092,  0.4217, -0.3364],
        [ 0.4796,  1.4135,  0.4042],
        [-1.4787,  0.1934, -0.7481]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4772, -0.2846,  0.5078],
        [-1.6357, -0.2045,  0.6094],
        [ 1.7790, -0.5137,  1.0132],
        [-0.7367, -0.9213,  0.6849],
        [ 0.4620, -0.6875, -2.4076]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [11]:
y = torch.rand(5, 3)
print(x + y)


tensor([[ 0.8701,  0.1310,  1.2984],
        [-1.2066,  0.3686,  0.7861],
        [ 1.9892,  0.2561,  1.0697],
        [-0.6743, -0.1745,  0.7955],
        [ 1.1630, -0.3206, -1.8169]])


In [12]:
print(torch.add(x, y))


tensor([[ 0.8701,  0.1310,  1.2984],
        [-1.2066,  0.3686,  0.7861],
        [ 1.9892,  0.2561,  1.0697],
        [-0.6743, -0.1745,  0.7955],
        [ 1.1630, -0.3206, -1.8169]])


In [16]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.8701,  0.1310,  1.2984],
        [-1.2066,  0.3686,  0.7861],
        [ 1.9892,  0.2561,  1.0697],
        [-0.6743, -0.1745,  0.7955],
        [ 1.1630, -0.3206, -1.8169]])


In [17]:
y.add_(x)
print(y)


tensor([[ 0.8701,  0.1310,  1.2984],
        [-1.2066,  0.3686,  0.7861],
        [ 1.9892,  0.2561,  1.0697],
        [-0.6743, -0.1745,  0.7955],
        [ 1.1630, -0.3206, -1.8169]])


In [18]:
print(x)
print(x[:,1])

tensor([[ 0.4772, -0.2846,  0.5078],
        [-1.6357, -0.2045,  0.6094],
        [ 1.7790, -0.5137,  1.0132],
        [-0.7367, -0.9213,  0.6849],
        [ 0.4620, -0.6875, -2.4076]])
tensor([-0.2846, -0.2045, -0.5137, -0.9213, -0.6875])


In [22]:
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [23]:
x= torch.randn(1)
print(x)
print(x.item())

tensor([-0.9260])
-0.9260037541389465


In [24]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [25]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [26]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [27]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [28]:
torch.cuda.is_available()

False