In [2]:
import numpy as np

In [3]:
streetlights = np.array([[1, 0, 1],
                         [0, 1, 1],
                         [0, 0, 1],
                         [1, 1, 1],
                         [0, 1, 1],
                         [1, 0, 1]])

In [4]:
walk_va_stop = np.array([[0],
                        [1],
                        [0],
                        [1],
                        [1],
                        [0]])

In [5]:
weight = np.array([0.5, 0.48, -0.7])

In [6]:
alpha = 0.1

In [7]:
walk_vs_stop = np.array([0, 1, 0, 1, 1, 0])

In [9]:
input = streetlights[0]
goal_prediction = walk_vs_stop[0]

In [17]:
for interation in range(10):
    prediction = input.dot(weight)
    delta = prediction - goal_prediction
    error = delta ** 2
    weight = weight - (alpha * (input * delta))
    
    print("Error:" + str(error) + " Prediction:" + str(prediction))

Error:1.0830740959956181e-15 Prediction:-3.291009109673837e-08
Error:6.93167419098793e-16 Prediction:-2.6328072832981775e-08
Error:4.436271463525054e-16 Prediction:-2.10624582219765e-08
Error:2.839213721690258e-16 Prediction:-1.6849966533172278e-08
Error:1.8170967579365226e-16 Prediction:-1.347997313771998e-08
Error:1.1629419442355685e-16 Prediction:-1.0783978598993826e-08
Error:7.442828596357192e-17 Prediction:-8.627182968012903e-09
Error:4.76341017906896e-17 Prediction:-6.9017462855924805e-09
Error:3.048582612683849e-17 Prediction:-5.521397117291826e-09
Error:1.9510929505814364e-17 Prediction:-4.417117782651303e-09


In [13]:
print(streetlights[0])

[1 0 1]


In [14]:
print(walk_vs_stop[0])

0


In [19]:
print(len(walk_vs_stop))

6


In [24]:
for interation in range(40):
    error_for_all_lights = 0
    for row_index in range(len(walk_vs_stop)):
        input = streetlights[row_index]
        goal_prediction = walk_vs_stop[row_index]
        
        prediction = input.dot(weight)
        
        delta = prediction - goal_prediction
        error = delta ** 2
        error_for_all_lights += error
        
        weight -= alpha * (input * delta)
        print("prediction: " + str(prediction))
    print("*" * 10 + "Error: " + str(error_for_all_lights))

prediction: -0.0019307298664941047
prediction: 0.9981968840915837
prediction: -0.014305232835570473
prediction: 1.012928991090041
prediction: 0.997402232338816
prediction: -0.0022597704706863973
**********Error: 0.0003906324012844786
prediction: -0.0018078163765491186
prediction: 0.9983285445557762
prediction: -0.013333927665753195
prediction: 1.0120510485201326
prediction: 0.9975860187071698
prediction: -0.0021145263649850997
**********Error: 0.00033938188821382463
prediction: -0.0016916210919880811
prediction: 0.9984494297114331
prediction: -0.01242856984735411
prediction: 1.0112327307565023
prediction: 0.9977558546025814
prediction: -0.001977514471556977
**********Error: 0.00029485619088725064
prediction: -0.0015820115772455824
prediction: 0.9985606362869454
prediction: -0.011584682422341355
prediction: 1.0104699868036406
prediction: 0.9979129799110622
prediction: -0.0018485000000912164
**********Error: 0.00025617262412587857
prediction: -0.0014788000000729735
prediction: 0.99866311

In [25]:
print(weight)

[ 7.61703562e-04  1.00076536e+00 -8.81382216e-04]


In [2]:
import numpy as np
np.random.seed(1)

In [3]:
def relu(x):
    return (x > 0) * x

In [4]:
print(relu(-5))

0


In [5]:
x = 5
y = (x > 0) * x

In [7]:
z = (x > 0)
print(z)

True


In [8]:
alpha = 0.2
hidden_size = 4

In [9]:
streetlights = ([[1, 0, 1],
                [0, 1, 1],
                [0, 0, 1],
                [1, 1, 1]])

In [11]:
walk_vs_stop = np.array([1, 1, 0, 0]).T

weight_0_1 = 2 * np.random.random((3, hidden_size)) - 1
weight_1_2 = 2 * np.random.random((hidden_size, 1)) - 1

In [13]:
print(np.random.random((3, hidden_size)))

[[0.4173048  0.55868983 0.14038694 0.19810149]
 [0.80074457 0.96826158 0.31342418 0.69232262]
 [0.87638915 0.89460666 0.08504421 0.03905478]]


In [19]:
layer_0 = streetlights[0]
layer_1 = relu(np.dot(layer_0, weight_0_1))
layer_2 = np.dot(layer_1, weight_1_2)

print(layer_0)
print(weight_0_1)
print(layer_1)
print(weight_1_2)
print(layer_2)

[1, 0, 1]
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
[-0.          0.51828245 -0.         -0.        ]
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]
[0.39194327]


In [22]:
a = "1 2 4"

In [23]:
print(int(a))

ValueError: invalid literal for int() with base 10: '1 2 4'