In [1]:
import numpy as np
weight = np.array([0.1, 0.2, 0])

In [2]:
def neural_network(input, weights):
    pred = input.dot(weights)
    return pred

In [3]:
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

In [4]:
input = np.array([toes[0], wlrec[0], nfans[0]])

In [5]:
pred = neural_network(input, weight)
print(pred)

0.9800000000000001


In [6]:
print(toes[0])

8.5


In [7]:
# toes % win # fans
ih_wgt = np.array([
    [0.1, 0.2, -0.1], # hid[0]
    [-0.1, 0.1, 0.9], # hid[1]
    [0.1, 0.4, 0.1]]).T # hid[2]

In [8]:
# hid[0] % hid[1] # hid[2]
hp_wgt = np.array([
    [0.3, 1.1, -0.3], # hurt?
    [0.1, 0.2, 0.0], # win?
    [0.0, 1.3, 0.1] # sad?
]).T

In [9]:
weights = [ih_wgt, hp_wgt]
def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred

In [10]:
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

In [11]:
input = np.array([toes[0], wlrec[0], nfans[0]])

In [12]:
pred = neural_network(input, weights)

In [13]:
print(pred)

[0.2135 0.145  0.5065]


In [14]:
a = np.zeros((2, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
b = np.zeros((4, 3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
c = a.dot(b)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
a = np.array([0, 1, 2, 3])
b = np.array([[0, 1, 2, 3],
             [4, 5, 6, 7]])

In [18]:
print(a * b)

[[ 0  1  4  9]
 [ 0  5 12 21]]
